matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      sudo: false
      language: scala
      addons:
        apt:
          packages:
            - graphviz
    - os: osx
      osx_image: xcode8
      language: java
      before_install:
        - brew update
        - brew install sbt

before_cache:
  - find $HOME/.sbt -name '*.lock' -delete
  - find $HOME/.ivy2 -name 'ivydata-*.properties' -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt compile
